import { Archivo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/page";

const archivo = Archivo({
    variable: "--font-archivo",
    subsets: ["latin"],
});

export const metadata = {
    title: "Agency Website",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${archivo.className}   antialiased `}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
