import { Archivo } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import Footer from '@/components/footer/Footer';
import Loader from '@/components/loader/Loader';
import CTA from '@/components/cta/CTA';
import SmoothScroll from '@/components/SmoothScroll/SmoothScroll';

const archivo = Archivo({
    variable: '--font-archivo',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Agency Website',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${archivo.className}   antialiased`}>
                <Loader>
                    <SmoothScroll>
                        <Navbar />
                        {children}
                        <CTA />
                        <Footer />
                    </SmoothScroll>
                </Loader>
            </body>
        </html>
    );
}
